[package]
name = "ichiyoAI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.29.1"

[dependencies.serenity]
version = "0.11.6"
optional = true
default-features = false
features = ["rustls_backend", "client", "gateway", "model", "cache"]
