[package]
name = "ichiyo_ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
chatgpt_rs = { version = "1.1" }
once_cell = "1.18"
tokio = { version = "1.29", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
version = "0.11"
features = ["client", "gateway", "model", "cache", "rustls_backend"]
default-features = false
