name: Release ichiyoAI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  discussions: write

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Bulid Docker Image
        run: |
          docker build --tag ghcr.io/approvers/ichiyo_ai:latest --tag ghcr.io/approvers/ichiyo_ai:${{ github.ref_name }} \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/approvers/ichiyo_ai:latest
          docker push ghcr.io/approvers/ichiyo_ai:${{ github.ref_name }}

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/checkout@v3

      - name: Create release to GitHub Repository
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ```shell
            docker pull ghcr.io/approvers/ichiyo_ai:${{ github.ref_name }}
            ```
          draft: true
