name: Release ichiyoAI

on:
  workflow_dispatch:
    inputs:
      tag:
        default: 'vX.Y.Z'
        description: 'A release version tag'
        required: true
        type: string

permissions:
  contents: write
  discussions: write

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Bulid Docker Image
        run: |
          docker build --tag ghcr.io/approvers/ichiyo_ai:latest --tag ghcr.io/approvers/ichiyo_ai:${{ inputs.tag }} \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/approvers/ichiyo_ai:latest
          docker push ghcr.io/approvers/ichiyo_ai:${{ inputs.tag }}

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/checkout@v3


      - name: Push tag
        run: |
          git tag -a ${{ inputs.tag }} -m "Release ${{ inputs.tag }}"
          git push origin ${{ inputs.tag }}

      - name: Create release to GitHub Repository
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ inputs.tag }}
          name: ichiyoAI ${{ inputs.tag }}
          body: |
            ```shell
            docker pull ghcr.io/approvers/ichiyo_ai:${{ inputs.tag }}
            ```
          draft: true
